import { Header } from '@/widgets/Header/Header';
import { Roboto } from 'next/font/google';
import '../configuration/styles/main.scss';
import { Providers } from '@/configuration/Providers/Providers';

const roboto = Roboto({
  weight: '400',
  style: 'normal',
  subsets: ['cyrillic', 'latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Providers>
          <Header />

          <main> {children}</main>
        </Providers>
      </body>
    </html>
  );
}
